name: bingo 
description: A friendly, Angular-like framework for Flutter, powered by code-gen.
version: 0.1.0 
repository: https://github.com/tugorez/bingo

environment:
  sdk: ^3.3.0 

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.6
